### ISSUE TITLE
Repo is behind published package on NPM

### ISSUE THREAD

**Issue by Xenokrates** [richard-vu/node-red-contrib-deepl#6]
Hi Richard,

thank you for your efforts to make Deep-L accessible from Node-RED.
I think it worth to invest time and to make this node usable.
- - -

- The currently committed version in this repo is `0.0.9`.
- The version published on NPM is `0.2.92` .

Please keep this repo up to date with the published versions.
Otherwise it is not possible to make PRs and to open issues.

Best regards
H.

**Comment by richard-vu** [comment]
Thank you sir, i will update in github. If you use for node red, you can this version node-red-contrib-deepl 0.2.92 in npm repo
